image: node:10

.template: &job_template
  script:
    - set -x
    - apt-get update && apt-get install -y build-essential texinfo ccache
    - /usr/sbin/update-ccache-symlinks
    - export CCACHE_DIR="$(pwd)/ccache"
    - export PATH="/usr/lib/ccache:$PATH"
    - npm install debug
    - ./travisLog.js npm install --build-from-source --unsafe-perm
    - npm run test
    - COMMIT_MESSAGE="${COMMIT_MESSAGE:-$(git show --format=%B -n 1 HEAD|head -n 1)}"; if fgrep -q '[publish]' <<<"${COMMIT_MESSAGE}"; then PUBLISH_BINARY=true; fi;
    - if [[ $PUBLISH_BINARY == true ]]; then $(npm bin)/node-pre-gyp package --target_arch=${BUILD_ARCH:-$(node mapping.js)} && $(npm bin)/node-pre-gyp-github publish -r; fi
    - npm run clean
    - npm install --fallback-to-build=false --unsafe-perm
    - npm run test

test_build_x64:
  <<: *job_template
  cache:
    key: test_build_x64
    paths:
      - ccache
  variables:
    DEBUG: node-musl
    BUILD_ARCH: x64

test_build_ia32:
  <<: *job_template
  cache:
    key: test_build_x64
    paths:
      - ccache
  variables:
    DEBUG: node-musl
    BUILD_ARCH: ia32
